### ISSUE TITLE
Error message to install the package

### ISSUE THREAD

**Issue by MaximePolicarpo** [GabrielNakamura/FishPhyloMaker#8]
Hi ! 

I tried to install your package with the command : 

devtools::install_github("GabrielNakamura/FishPhyloMaker", ref = "main", build_vignettes = TRUE)

Unfortunately, it returned an error message that I paste below : 

_Erreur : Failed to install 'FishPhyloMaker' from GitHub:
  System command 'R' failed, exit status: 134, stdout + stderr (last 10 lines):
E> dyld: lazy symbol binding failed: Symbol not found: _utimensat
E>   Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
E>   Expected in: /usr/lib/libSystem.B.dylib
E> 
E> dyld: Symbol not found: _utimensat
E>   Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
E>   Expected in: /usr/lib/libSystem.B.dylib
E> 
E> /Library/Frameworks/R.framework/Resources/bin/build: line 10:  9042 Done                    echo 'tools:::.build_packages()'
E>       9043 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" --no-restore --no-echo --args ${args}_

Thank for any help provided ! 

Best regards,

Maxime Policarpo

**Comment by GabrielNakamura** [comment]
Hi Maxine, thanks to report. I will check this error. At this moment i
suggest to you to check the package updates and R version.
I expect to return to you soon

Em seg, 10 de mai de 2021 11:53, MaximePolicarpo ***@***.***>
escreveu:

**Comment by GabrielNakamura** [comment]
Hi Maxime, please, check out the updates of your packages. This error may be related to some dependencies or package dependencies that you need to update before install FishPhyloMaker.

Any bugs don't hesitate to contact me

Best
Gabriel
